name: release

on:
  push:
    branches:
      - release  # Trigger only on pushes to the 'release' branch

permissions:
  id-token: write  # Required for Trusted Publisher OIDC
  contents: read   # Required to read repo contents

environment:
  name: release  # GitHub environment name

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        repository-url: https://upload.pypi.org/legacy/
